# node:14-alpine
FROM node@sha256:9a28dee760ed940c6b72bd0b5aca05cdb04a05f4328f6308c59b3d59903e5c30 as builder

WORKDIR /usr/src/app

RUN apk add git openssh-client

COPY package.json package-lock.json ./

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh,id=github npm install

COPY . .
RUN ./node_modules/.bin/ng build --prod

# nginx:1.19-alpine
FROM nginx@sha256:a3c6118edc80de4a5aaf2711b7742c25d4d2da54325bae465205cb386afa79ee

COPY ./docker/nginx-ssl.conf /etc/nginx/nginx.conf
COPY ./cert.pem /etc/nginx/cert.pem
COPY ./key.pem /etc/nginx/key.pem
COPY --from=builder /usr/src/app/dist/jamfactory-web /usr/share/nginx/html
