FROM node:18-alpine as builder

WORKDIR /usr/src/app

RUN apk add git openssh-client python3 make gcc g++

COPY package.json package-lock.json ./

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh,id=github npm install

COPY . .
RUN ./node_modules/.bin/ng build --prod

FROM nginx:1.23-alpine

COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/dist/jamfactory-web /usr/share/nginx/html
