# node:14
FROM node:14 as builder

WORKDIR /usr/src/app

RUN apk add git openssh-client

COPY package.json package-lock.json ./

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh,id=github npm install

COPY . .
RUN ./node_modules/.bin/ng build --prod

# nginx:1.19-alpine
FROM nginx@sha256:a3c6118edc80de4a5aaf2711b7742c25d4d2da54325bae465205cb386afa79ee

COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/dist/jamfactory-web /usr/share/nginx/html
